# Minimal config for Intelligent Inference Router (project root)
api_keys:
  - "example-key"
providers:
  openai:
    api_key: "${OPENAI_API_KEY}"
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"
  huggingface:
    api_key: "${HUGGINGFACE_API_KEY}"
  openrouter:
    api_key: "${OPENROUTER_API_KEY}"
  veniceai:
    api_key: "${VENICEAI_API_KEY}"
services:
  dummy_service:
    url: "http://localhost:1234"
